### ISSUE TITLE
Expected format of rcm_lang_tagged.txt

### ISSUE THREAD

**Issue by maheshmylavarapu0057** [microsoft/CodeMixed-Text-Generator#3]
HI,
I am exploring this project.I would like to use SPF as sampling method.I found that rcm_lang_tagged.txt file is not present in your project.I understand that this is file should have  real codemix dataset of language pair.I  would like to know the format of how this data file should be. Please provide with a sample rcm_lang_tagged.txt file of hindi-english codemix data.
Thanks

**Comment by AmirHussein96** [comment]
The rcm_lang_tagged.txt still seems to be missing.

**Comment by mohdsanadzakirizvi** [comment]
It's not missing, that's the file containing Real Code Mixed (or RCM) data that the user has to provide. We used a small dataset off twitter in our internal experiments for the same which we can't release. You can get any real-world code-mixed data and save it in a file with this name and start the entire pipeline.

**Comment by mohdsanadzakirizvi** [comment]
There is no specific format required for this file, it should just contain code-mixed sentences, each on a new line just like a regular txt file.

**Comment by mohdsanadzakirizvi** [comment]
You can also give this file any name of your choice and update the [parameter in the config file](https://github.com/microsoft/CodeMixed-Text-Generator/blob/b2dd0c38003f3fa4b37f1bd063a2028f72a7bfe7/CodeMixed-Text-Generator/config.ini#L57).

**Comment by AmirHussein96** [comment]
Thank you @mohdsanadzakirizvi
